### ISSUE TITLE
can not login with user created.

### ISSUE THREAD

**Issue by kuzco9x** [FraGoTe/admin-dashboard-zend#4]
get logged in by /dashboard/login with user created in database but can not login.
can you help me?

**Comment by FraGoTe** [comment]
Did you encrypt your password?

**Comment by kuzco9x** [comment]
Im already choose MD5 in db.

**Comment by kuzco9x** [comment]
Found it, SHA1(), thanks for your hint.

**Comment by FraGoTe** [comment]
nice man!
